src/Entity/Client.php
<?php

namespace App\Entity;

use App\Repository\ClientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: ClientRepository::class)]
/**
 * @Vich\Uploadable
 */
class Client
{
    #[ORM\Id]
    #[ORM\Column(type: 'string', length: 10)]
    private $numcli;

    #[ORM\Column(type: 'string', length: 255)]
    private $nom;

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * 
     * @Vich\UploadableField(mapping="client_image", fileNameProperty="imageName")
     * 
     * @var File|null
     */
    private $imageFile;
    
    #[ORM\Column(type: 'string', length: 255, nullable: true)]
    private $imageName;

    #[ORM\OneToMany(mappedBy: 'clients', targetEntity: Commande::class, orphanRemoval: true)]
    private $commandes;

    #[ORM\OneToMany(mappedBy: 'client', targetEntity: Facture::class)]
    private $factures;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
        $this->commandes = new ArrayCollection();
        $this->factures = new ArrayCollection();
    }

    public function getNumcli(): ?string
    {
        return $this->numcli;
    }

    public function setNumcli(string $numcli): self
    {
        $this->numcli = $numcli;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }
    
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        $this->produits->removeElement($produit);

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
            $commande->setClients($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            // set the owning side to null (unless already changed)
            if ($commande->getClients() === $this) {
                $commande->setClients(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Facture>
     */
    public function getFactures(): Collection
    {
        return $this->factures;
    }

    public function addFacture(Facture $facture): self
    {
        if (!$this->factures->contains($facture)) {
            $this->factures[] = $facture;
            $facture->setClient($this);
        }

        return $this;
    }

    public function removeFacture(Facture $facture): self
    {
        if ($this->factures->removeElement($facture)) {
            // set the owning side to null (unless already changed)
            if ($facture->getClient() === $this) {
                $facture->setClient(null);
            }
        }

        return $this;
    }
}

src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Client::class, inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false, referencedColumnName: 'numcli')]
    private $clients;

    #[ORM\ManyToOne(targetEntity: Produit::class, inversedBy: 'commandes')]
    #[ORM\JoinColumn(nullable: false, referencedColumnName: 'num_pro')]
    private $produits;

    #[ORM\Column(type: 'integer')]
    private $qte;

    #[ORM\Column(type: 'date')]
    private $date_commande;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClients(): ?Client
    {
        return $this->clients;
    }

    public function setClients(?Client $clients): self
    {
        $this->clients = $clients;

        return $this;
    }

    public function getProduits(): ?Produit
    {
        return $this->produits;
    }

    public function setProduits(?Produit $produits): self
    {
        $this->produits = $produits;

        return $this;
    }

    public function getQte(): ?int
    {
        return $this->qte;
    }

    public function setQte(int $qte): self
    {
        $this->qte = $qte;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    public function setDateCommande(\DateTimeInterface $date_commande): self
    {
        $this->date_commande = $date_commande;

        return $this;
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\Validator\Constraints\NotBlank;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Numcli', TextType::class, [
                'attr' => [
                    'readOnly' => true,
                ]
            ])
            ->add('Nom', TextType::class, [
                'label' => 'Noms: ',
                'constraints' => [
                    new NotBlank([
                        'message' => 'This field cannot be empty.'
                    ])
                ]
            ])
            ->add('imageFile', VichImageType::class, [
                'label' => 'Upload Image(PNG or JPG)',
                'required' => false,
                'allow_delete' => true,
                'download_uri' => false,
                'imagine_pattern' => 'squared_thumbnail_small'
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Client::class,
            'required' => false
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Class\NumberToStr;
use App\Entity\Client;
use App\Entity\ClientHistory;
use App\Entity\Facture;
use App\Form\BillType;
use App\Form\ClientType;
use App\Repository\ClientHistoryRepository;
use App\Repository\ClientRepository;
use App\Repository\CommandeRepository;
use App\Repository\FactureRepository;
use DateTime;
use DateTimeImmutable;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Component\Pager\PaginatorInterface;
use Knp\Snappy\Pdf;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Length;

class ClientController extends AbstractController
{   
    #[Route('/', name: 'home')]
    public function home()
    {
        return $this->render('accueil/home.html.twig');
    }
    /**
     * set allowed method as POST/GET
     * 
     * We apply this method for adding a new client into our database
     * 
     * @return a Response object
    */
    #[Route('/client/add', name: 'client_create', methods: ['GET', 'POST'])]
    public function create(ClientHistoryRepository $rep, Request $req, EntityManagerInterface $em): Response
    {
        $client = new Client;
        $history = new ClientHistory;

        $numb = $rep->findAll();

        #filter its identifier so we can get the number after 'CL' 
        if(count($numb) === 0){
            $client->setNumcli('CL01');
        }else{        
            $client->setNumcli(count($numb)<9? 'CL0'.count($numb)+1:'CL'.count($numb)+1);
        }

        $form = $this->createForm(ClientType::class, $client);

        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid()){
            $history->setNom($client->getNom());

            $em->persist($history);
            $em->persist($client);
            $em->flush();

            $this->addFlash('success', 'Client ajouté avec succès!');

            return $this->redirectToRoute('client_list');
        }
        return $this->render('client/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     * set allowed method as PATCH/GET
     * 
     * @return a Response object
    */
    #[Route('/client/modify/{id}', name: 'client_edit', methods: ['GET', 'PATCH'])]
    public function modify(Client $client, Request $req, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(ClientType::class, $client, [
            'method' => 'PATCH'
        ]);

        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid()){
            $em->flush();

            $this->addFlash('success', 'Client '.$client->getNumcli().' modifié avec succès');

            return $this->redirectToRoute('client_list');
        }

        return $this->render('client/modify.html.twig', [
            'form' => $form->createView(),
            'client' => $client
        ]);
    }

    /**
     * render all clients from the database
     * 
     * @return a Response Object
    */
    #[Route('/client', name: 'client_list', methods: ['GET'])]
    public function list(ClientRepository $rep, PaginatorInterface $paginator, Request $req): Response
    {
        $clients = $rep->findAll();

        $pagination = $paginator->paginate(
            $clients,
            $req->query->getInt('page', 1),
            10
        );

        # use GET method
        # disable csrf protection
        $form = $this->createFormBuilder(null, ['method' => 'GET', 'csrf_protection' => false])
            ->add('search', TextType::class, [
                'label' => ' ',
                'attr' => [
                    'placeholder' => "Tapez le nom ou l'identifiant du client",
                ],
                'required' => false
            ])
            ->getForm();
        
        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid()){
            $specificClients = $rep->search($form->getData()['search']);
            $pagination = $paginator->paginate(
                $specificClients,
                $req->query->getInt('page', 1),
                10
            );

            if($form->getData()['search'] !== null)
                return $this->render('client/list.html.twig', [
                    'pagination' => $pagination,
                    'form' => $form->createView()
                ]); 
        }
        

        return $this->render('client/list.html.twig', [
            'pagination' => $pagination,
            'form' => $form->createView()
        ]);
    }

    /**
     * set allowed method as DELETE.
     * 
     * DELETE is among the HTTP method which is used for deletion
     * 
     * @return a Response object
    */
    #[Route('/client/delete/{id}', name: 'client_delete', methods: ['DELETE'])]
    public function delete(Client $client, Request $req, EntityManagerInterface $em): Response
    {
        //csrf protection
        if($this->isCsrfTokenValid('client_deletion_'.$client->getNumcli(), $req->request->get('csrf_token'))){
            $em->remove($client);

            $this->addFlash('success', 'Client '.$client->getNumcli().' supprimé avec succès');
            $em->flush();
        }

        return $this->redirectToRoute('client_list');
    }
    
    #[Route('/client/productList/{id}', name: 'client_product_list', methods: ['GET'])]
    public function show(Client $client, CommandeRepository $rep, Request $req): Response
    {
        $commandListPerClient = $rep->findBy(['clients' => $client]);

        # use GET method
        # disable csrf protection
        $form = $this->createFormBuilder(null, ['method' => 'GET', 'csrf_protection' => false])
            ->add('beginningDate', DateType::class, [
                'widget' => 'single_text',
                'required' => false,
                'attr' => [
                    'title' => 'Début'
                ]
            ])
            ->add('lastDate', DateType::class, [
                'widget' => 'single_text',
                'required' => false,
                'attr' => [
                    'title' => 'Fin'
                ]
            ])
            ->getForm()
        ;

        # set the current time as the default value of the lastDate field
        $form->get('lastDate')->setData(new DateTime);
        
        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid() && 
            $form->getData()['beginningDate'] !== null && $form->getData()['lastDate'] !== null){
                $commands = $rep->findAllCommandBetweenTwoDates($form->getData()['beginningDate'], $form->getData()['lastDate']);
                return $this->render('client/show.html.twig',[
                    'client' => $client,
                    'form' => $form->createView(),
                    'commands' => $commands
                ]);    
        }

        return $this->render('client/show.html.twig',[
            'client' => $client,
            'form' => $form->createView(),
            'commands' => $commandListPerClient
        ]);
    }

    #[Route(path: '/client/turnover', name: 'clients_turnover', methods: ['GET'])]
    public function turnOver(CommandeRepository $rep, Request $req, PaginatorInterface $paginator): Response
    {
        #create form to filter data
        $form = $this->createFormBuilder(null, ['method' => 'GET', 'csrf_protection' => false])
            ->add('year', NumberType::class, [
                'required' => false,
                'attr' => [
                    'placeholder' => "Tapez une année",
                    'min' => 1,
                    'max' => date('Y')
                ],
                'constraints' => [
                    new Length([
                        'min' => 1,
                        'minMessage' => 'Le champ devra contenir au moins {{ min }} caractère',
                        'max' => 4,
                        'maxMessage' => 'Le champ devra contenir au plus {{ max }} caractère'
                    ]),
                ]
            ])
            ->getForm()
        ;
        $clients = $rep->findAllTurnOversPerClient();
        
        #set the current year as default value
        $form->get('year')->setData(date('Y'));
        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid() && $form->getData()['year'] !== null){
            $clients = $rep->findAllTurnOversPerClient($form->getData()['year']);

            $pagination = $paginator->paginate(
                $clients,
                $req->query->getInt('page', 1),
                10
            );

            if($clients)
                return $this->render('client/turnOver.html.twig', [
                    'pagination' => $pagination,
                    'form' => $form->createView(),
                    'year' => $form->get('year')->getData() 
                ]);
        }

        $pagination = $paginator->paginate(
            $clients,
            $req->query->getInt('page', 1),
            10
        );
        
        return $this->render('client/turnOver.html.twig', [
            'pagination' => $pagination,
            'form' => $form->createView(),
            'year' => date('Y') 
        ]);
    }

    #[Route(path: '/bill/generate', name: 'generate_bill', methods: ['GET', 'POST'])]
    public function factureGenerate(Request $req, EntityManagerInterface $em,FactureRepository $factRep, 
        CommandeRepository $rep,Pdf $knpSnappyPdf): Response
    {
        $facture = new Facture;
        $facture->setDateFacture(new DateTimeImmutable);

        $form = $this->createForm(BillType::class, $facture);

templates/client/create.html.twig
{% extends 'base.html.twig' %}

{% block title 'Add Client' %}

{% block body %}
    {{ form_start(form) }}
        {{ form_widget(form) }}

        <input type="submit" value="Ajouter">
    {{ form_end(form) }}
{% endblock %}

templates/client/list.html.twig
{% extends "base.html.twig" %}

{% block title 'liste des clients' %}

{% block body %}

    <div class="container">
        {{ form_start(form) }}
            {{ form_widget(form) }}

            <input type="submit" value="Rechercher">
        {{ form_end(form) }}

        {% if pagination|length == 0 %}
            <p>Il n'y aucune correspondance à votre spécification.</p>
        {% else %}
            <table class="table table-hover table-secondary table-bordered caption-top mx-auto mt-3">
                <tr class="table-dark row">
                    <th class="text-center col-3">N°CLIENT</th>
                    <th class="text-center col-5">NOM</th>
                    <th class="text-center col-1">PHOTO</th>
                    <th class="text-center col-3">ACTIONS</th>
                </tr>

                {# table body #}
                {% for client in pagination %}
                    <tr class="row px-auto align-middle">
                        <td class="text-center col-3"><span class="align-middle">{{ client.numcli }}</span></td>
                        <td class="text-center col-5"><span class="align-middle">{{ client.nom }}</span></td>
                        <td class="text-center col-1"><img src="{{ (client.imageName? vich_uploader_asset(client) : 'Avatar/jeune-homme-avatar-personnage-photo-de-profil-tc667n.jpg')
                    | imagine_filter('squared_thumbnail_small') }}" class="img-thumbnail rounded mx-auto" /></td>
                        <td class="text-center col-3">
                            <button class="btn btn-dark" title="modifier {{ client.numcli }}">
                                <a href="{{ path('client_edit', {id:client.numcli}) }}" class="text-decoration-none">
                                    <img src="/icon/edit.png" alt="edit-icon">
                                </a>
                            </button>
                            <button class="btn btn-primary m-1">
                                <a href="#" class="text-decoration-none" onclick="event.preventDefault();confirm('are you sure?') && 
                                document.getElementById('js-client-delete-form_{{ client.numcli }}').submit();">
                                    <img src="/icon/delete.png" alt="delete-icon">
                                </a>
                            </button>

                            <button class="btn btn-success">
                                <a href="#" class="text-decoration-none" onclick="event.preventDefault();confirm('are you sure?') && 
                                document.getElementById('js-client-delete-form_{{ client.numcli }}').submit();">
                                    <img src="/icon/product.png" alt="delete-icon">
                                </a>
                            </button>
                        </td>
                    </tr>

                    <form id='js-client-delete-form_{{ client.numcli }}' action="{{ path('client_delete', { id:client.numcli }) }}" method="post" style="display: none;">
                        <input type="hidden" name="csrf_token" value="{{ csrf_token('client_deletion_'~client.numcli) }}">
                        <input type="hidden" name="_method" value="DELETE">
                    </form>
                {% endfor %}
            </table>

            {# display navigation #}
            <div class="d-flex justify-content-center">
                {{ knp_pagination_render(pagination) }}
            </div>
        {% endif %}

    </div>
        
{% endblock %}

templates/client/modify.html.twig
{% extends "base.html.twig" %}

{% block title 'modify client' %}

{% block body %}
    {{ form_start(form) }}
        {{ form_widget(form) }}

        <input type="submit" value="Modifier">
    {{ form_end(form) }}
{% endblock %}

templates/client/show.html.twig
{% extends "base.html.twig" %}

{% block title client.nom~' profil' %}

{% block body %}
    {{ form_start(form) }}
        {{ form_widget(form) }}

        <input type="submit" value="Rechercher">
    {{ form_end(form) }}
    
    <p>><img src="{{ (client.imageName? vich_uploader_asset(client) : 'Avatar/jeune-homme-avatar-personnage-photo-de-profil-tc667n.jpg')
    |imagine_filter('squared_thumbnail_small') }}" /></p>
    <h1>{{ client.nom }}</h1>
    {% if commands|length == 0 %}
        <p>Ce client n'a rien commandé pour l'instant.</p>
    {% else %}
        <table>
            <thead>
                <td>NumPro</td>
                <td>Designation</td>
                <td>Prix Unitaire</td>
                <td>Date de la commande</td>
            </thead>

            {% for command in commands %}
                <tr>
                    <td>{{ command.produits.numPro }}</td>
                    <td>{{ command.produits.design }}</td>
                    <td>{{ command.produits.pu }}</td>
                    <td>{{ command.dateCommande|date('d/m/Y') }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}

templates/client/turnOver.html.twig
{% extends "base.html.twig" %}

{% block title "Chiffres d'affaires"%}

{% block body %}
    {{ form_start(form) }}
        {{ form_widget(form) }}

        <input type="submit" value="Rechercher">
    {{ form_end(form) }}

    {% if clients|length == 0 %}
        <p>Aucun résultat</p>
    {% else %}
        <table>
            <thead>
                <td>N°CLIENT</td>
                <td>NOM</td>
                <td>CHIFFRE D’AFFAIRES</td>
            </thead>

            {% for client in clients %}
                <tr>
                    <td>{{ client[0].numcli }}</td>
                    <td>{{ client[0].nom }}</td>
                    <td>{{ client[1] }}</td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}
{% endblock %}